name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update firebaseConfig in FirebaseData.js
        run: |
          CONFIG_BLOCK="const firebaseConfig = {
            apiKey: '${{ secrets.API }}',
            authDomain: '${{ secrets.AUTH_DOMAIN }}',
            databaseURL: '${{ secrets.URL }}',
            projectId: '${{ secrets.PRJ_ID }}',
            storageBucket: '${{ secrets.BUCKET }}',
            messagingSenderId: '${{ secrets.MSG_ID }}',
            appId: '${{ secrets.ID }}'
          };"

          sed -i "/const firebaseConfig = {/,/^};/c\\$CONFIG_BLOCK" FirebaseData.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
