name: Build and Deploy

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholder with Firebase config
        run: |
          FIREBASE_CONFIG="const firebaseConfig = {
            apiKey: '${{ secrets.API }}',
            authDomain: '${{ secrets.AUTH_DOMAIN }}',
            databaseURL: '${{ secrets.URL }}',
            projectId: '${{ secrets.PRJ_ID }}',
            storageBucket: '${{ secrets.BUCKET }}',
            messagingSenderId: '${{ secrets.MSG_ID }}',
            appId: '${{ secrets.ID }}'
          };"

          # Replace the line in FirebaseData.js
          sed -i "s|const firebaseConfig = __FIREBASE_CONFIG__;|$FIREBASE_CONFIG|" FirebaseData.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # if your index.html is in the root
