- name: Update firebaseConfig in FirebaseData.js
  run: |
    cat > new_config.js <<EOF
const firebaseConfig = {
  apiKey: '${{ secrets.API }}',
  authDomain: '${{ secrets.AUTH_DOMAIN }}',
  databaseURL: '${{ secrets.URL }}',
  projectId: '${{ secrets.PRJ_ID }}',
  storageBucket: '${{ secrets.BUCKET }}',
  messagingSenderId: '${{ secrets.MSG_ID }}',
  appId: '${{ secrets.ID }}'
};
EOF

    # Replace firebaseConfig block in FirebaseData.js with the content of new_config.js
    sed -i "/const firebaseConfig = {/,/^};/{
      r new_config.js
      d
    }" FirebaseData.js
