name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Firebase config block
      run: |
        FIREBASE_CONFIG="const firebaseConfig = {
          apiKey: '${{ secrets.API_KEY }}',
          authDomain: '${{ secrets.AUTH_DOMAIN }}',
          databaseURL: '${{ secrets.DATABASE_URL }}',
          projectId: '${{ secrets.PROJECT_ID }}',
          storageBucket: '${{ secrets.STORAGE_BUCKET }}',
          messagingSenderId: '${{ secrets.MSG_ID }}',
          appId: '${{ secrets.APP_ID }}'
        };"

        # Replace the firebaseConfig object in FirebaseData.js
        sed -i "/const firebaseConfig = {/,/^};/c\\$FIREBASE_CONFIG" FirebaseData.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        enable_jekyll: false
