- name: Update firebaseConfig in FirebaseData.js
  run: |
    cat > new_config.js <<EOF
const firebaseConfig = {
  apiKey: '${{ secrets.API }}',
  authDomain: '${{ secrets.AUTH_DOMAIN }}',
  databaseURL: '${{ secrets.URL }}',
  projectId: '${{ secrets.PRJ_ID }}',
  storageBucket: '${{ secrets.BUCKET }}',
  messagingSenderId: '${{ secrets.MSG_ID }}',
  appId: '${{ secrets.ID }}'
};
EOF

    awk '
      BEGIN {inside=0}
      /const firebaseConfig = {/ {print ""; print ""; system("cat new_config.js"); inside=1; next}
      /^};/ && inside {inside=0; next}
      !inside {print}
    ' FirebaseData.js > FirebaseData.tmp && mv FirebaseData.tmp FirebaseData.js
