name: Build and Deploy

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholder with Firebase config
  run: |
    sed -i "/const firebaseConfig = __FIREBASE_CONFIG__;/c\const firebaseConfig = {" FirebaseData.js
    echo "  apiKey: '${{ secrets.API }}'," >> FirebaseData.js
    echo "  authDomain: '${{ secrets.AUTH_DOMAIN }}'," >> FirebaseData.js
    echo "  databaseURL: '${{ secrets.DATABASE_URL }}'," >> FirebaseData.js
    echo "  projectId: '${{ secrets.PRJ_ID }}'," >> FirebaseData.js
    echo "  storageBucket: '${{ secrets.BUCKET }}'," >> FirebaseData.js
    echo "  messagingSenderId: '${{ secrets.MSG_ID }}'," >> FirebaseData.js
    echo "  appId: '${{ secrets.ID }}'" >> FirebaseData.js
    echo "};" >> FirebaseData.js


          # Replace the line in FirebaseData.js
          sed -i "s|const firebaseConfig = __FIREBASE_CONFIG__;|$FIREBASE_CONFIG|" FirebaseData.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # if your index.html is in the root
