name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main  # or change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FIREBASE_CONFIG: |
        const firebaseConfig = {
          apiKey: "${{ secrets.FIREBASE_API_KEY }}",
          authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
          databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
          storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
          messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
          appId: "${{ secrets.FIREBASE_APP_ID }}"
        };

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace firebaseConfig in FirebaseData.js
        run: |
          echo "Replacing firebaseConfig block..."
          CONFIG=$(printf '%s\n' "$FIREBASE_CONFIG")
          sed -i '/const firebaseConfig = {/,/^};/c\'"$CONFIG" FirebaseData.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          exclude_assets: .github
          enable_jekyll: false
